name: "Docs CI"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - name: Update git profile
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: mkdocs gh-deploy --force
